// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApONZ51jX0onQDCkKQix5EjHXd-e1fop8',
    appId: '1:138906272420:web:1d32aa24f31ab077311c31',
    messagingSenderId: '138906272420',
    projectId: 'newchatapp-36361',
    authDomain: 'newchatapp-36361.firebaseapp.com',
    storageBucket: 'newchatapp-36361.appspot.com',
    measurementId: 'G-27B6QS2J6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz8DCKbmwb8HYCkJLjNrS5U9BtfSkRDDg',
    appId: '1:138906272420:android:e75e8a908018c224311c31',
    messagingSenderId: '138906272420',
    projectId: 'newchatapp-36361',
    storageBucket: 'newchatapp-36361.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8EyPOrgngRrCwOMXNzZCBXAxtRorWfVs',
    appId: '1:138906272420:ios:a8561fd454badb43311c31',
    messagingSenderId: '138906272420',
    projectId: 'newchatapp-36361',
    storageBucket: 'newchatapp-36361.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
